# This is a basic workflow to help you get started with Actions

name: Run Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Run server
        run: npm start
